@startuml ウォレット作成フロー

actor "ウォレットアプリケーション" as app 
participant "SDK in Server" as ssdk #aqua
participant WalletAPI as api #Yellow
database DB as db

note over app
サインアップボタン押下
end note

app -> api : [call] サインアップ API 呼び出し
note right app
[request]
・email
・password
end note

api -> api : authCode を生成

api -> db : authCode 保存

api -> app : authCode 返却

app -> api : [call] verify auth code API 呼び出し

api -> db : authCode チェック

app -> app : 通信用公開鍵の生成

note right app
[request]
・email
・password
・通信用公開鍵
end note

api -> ssdk : ウォレット生成関数呼び出し
return walletAddress secretKey

api -> db : 会員情報とwallet addressをuserテーブルに保存

api -> app : ユーザーIDを返却

note right api
[response]
・userID
・walletAddress
end note

@enduml